#ifndef COMMON2DOWNLINK_H_RTIHU
#define COMMON2DOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _commonRtWodPayload_t {
    unsigned int AutoSafeAllowed:1;       //Offset=0
    unsigned int AutoSafeModeActive:1;       //Offset=1
    unsigned int transponderEnabled:1;       //Offset=2
    unsigned int TLMresets:8;       //Offset=3
    unsigned int wodSize:8;       //Offset=11
    unsigned int swCmds:32;       //Offset=19
    unsigned int hwCmdCnt:8;       //Offset=51
    unsigned int swCmdCntICR:8;       //Offset=59
    unsigned int swCmdCntDCT:8;       //Offset=67
    unsigned int DCT1Status:8;       //Offset=75
    unsigned int DCT2Status:8;       //Offset=83
    unsigned int LMRAMstatus:8;       //Offset=91
    unsigned int PrimMRAMstatus:8;       //Offset=99
    unsigned int SecndMRAMstatus:8;       //Offset=107
} commonRtWodPayload_t; // Total Size=115 bits or 14.375 bytes with 3 left over
#endif
