#ifndef COMMONDOWNLINK_H_RTIHU
#define COMMONDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _commonRtMinmaxWodPayload_t {
    uint8_t DCT1Power;       //Offset=0
    uint8_t DCT2Power;       //Offset=8
    uint8_t DCT1RSSI;       //Offset=16
    uint8_t DCT2RSSI;       //Offset=24
    uint8_t DCT1RlftdPower;       //Offset=32
    uint8_t busV;       //Offset=40
    uint8_t TxPAi;       //Offset=48
    uint8_t TxTemp;       //Offset=56
    uint8_t FwdPower;       //Offset=64
    uint8_t pad30[2];       //Offset=72
} commonRtMinmaxWodPayload_t; // Total Size=88 bits or 11 bytes with 0 left over
#endif
