#ifndef COMMON2DOWNLINK_H_RTIHU
#define COMMON2DOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _commonRtWodPayload_t {
    unsigned int pad202:7;       //Offset=0
    unsigned int PowerFlagAx5043:1;       //Offset=7
    unsigned int PowerFlagSSPA:1;       //Offset=8
    unsigned int PowerFlagLNA:1;       //Offset=9
    unsigned int PowerFlag5V:1;       //Offset=10
    unsigned int DigiEnabled:1;       //Offset=11
    unsigned int uplinkEnabled:1;       //Offset=12
    unsigned int pbEnabled:1;       //Offset=13
    unsigned int AutoSafeModeActive:1;       //Offset=14
    unsigned int AutoSafeAllowed:1;       //Offset=15
    uint8_t LogLevel;       //Offset=16
    uint8_t TimePeriod;       //Offset=24
    uint8_t TelemPeriod;       //Offset=32
    uint8_t WodPeriod;       //Offset=40
    uint8_t MaxWodFileSize;       //Offset=48
    uint8_t MaxExpFileSize;       //Offset=56
    uint8_t PbStatusPeriod;       //Offset=64
    uint8_t PbTimeout;       //Offset=72
    uint8_t UplinkStatusPeriod;       //Offset=80
    uint8_t swCmdCnt;       //Offset=88
    uint8_t TLMresets;       //Offset=96
    uint8_t pad203[3];       //Offset=104
    uint32_t swCmds;       //Offset=128
    uint8_t MRAMstatus0;       //Offset=160
    uint8_t MRAMstatus1;       //Offset=168
    uint8_t MRAMstatus2;       //Offset=176
    uint8_t MRAMstatus3;       //Offset=184
    uint8_t TXPwrMode;       //Offset=192
    uint8_t TxModMode;       //Offset=200
    uint8_t RX0PwrMode;       //Offset=208
    uint8_t RX1PwrMode;       //Offset=216
    uint8_t RX2PwrMode;       //Offset=224
    uint8_t RX3PwrMode;       //Offset=232
    uint8_t RX0ModMode;       //Offset=240
    uint8_t RX1ModMode;       //Offset=248
    uint8_t RX2ModMode;       //Offset=256
    uint8_t RX3ModMode;       //Offset=264
    uint8_t IntoAutoSafe;       //Offset=272
    uint8_t OutofAutoSafe;       //Offset=280
} commonRtWodPayload_t; // Total Size=192 bits or 24 bytes with 0 left over
#endif
