#ifndef HEADERDOWNLINK_H_RTIHU
#define HEADERDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _header_t {
    uint8_t satelliteID;       //Offset=0
    uint8_t type;       //Offset=8
    uint16_t resetCnt;       //Offset=16
    uint32_t uptime;       //Offset=32
    uint8_t protocolVersion;       //Offset=64
    uint8_t versionMajor;       //Offset=72
    uint8_t versionMinor;       //Offset=80
    unsigned int pad17:5;       //Offset=88
    unsigned int inScienceMode:1;       //Offset=93
    unsigned int inHealthMode:1;       //Offset=94
    unsigned int inSafeMode:1;       //Offset=95
} header_t; // Total Size=96 bits or 12 bytes with 0 left over
#endif
