#ifndef HEADERDOWNLINK_H_RTIHU
#define HEADERDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _header_t {
    uint32_t uptime;       //Offset=0
    uint16_t resetCnt;       //Offset=32
    uint8_t protocolVersion;       //Offset=48
    uint8_t versionMajor;       //Offset=56
    uint8_t versionMinor;       //Offset=64
    uint8_t spacecraftMode;       //Offset=72
} header_t; // Total Size=80 bits or 10 bytes with 0 left over
#endif
