#ifndef INFREQUENTDOWNLINK_H_RTIHU
#define INFREQUENTDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _infrequentDownlink_t {
    uint32_t Uptime;       //Offset=0
    uint32_t secsInEpoch;       //Offset=32
    unsigned int UTCHours:5;       //Offset=32
    unsigned int UTCMinutes:6;       //Offset=37
    unsigned int UTCSeconds:6;       //Offset=43
    unsigned int UTCDay:5;       //Offset=49
    unsigned int UTCMonth:4;       //Offset=54
    unsigned int UTCYear:5;       //Offset=58
    unsigned int UTCValid:1;       //Offset=63
    uint8_t EnterAutosafe;       //Offset=64
    uint8_t ExitAutosafe;       //Offset=72
    uint16_t pad266;       //Offset=80
} infrequentDownlink_t; // Total Size=96 bits or 12 bytes with 0 left over
#endif
