#ifndef LEGACYERRORSDOWNLINK_H_RTIHU
#define LEGACYERRORSDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _legacyErrors_t {
    unsigned int LegWdReports:9;       //Offset=96
    unsigned int LegErrorCode:5;       //Offset=105
    unsigned int LegTaskNumber:4;       //Offset=110
    unsigned int LegPreviousTask:4;       //Offset=114
    unsigned int LegEarlyResetCount:3;       //Offset=118
    unsigned int LegWasStillEarlyInBoot:1;       //Offset=121
    unsigned int LegValid:1;       //Offset=122
    unsigned int LegFiller1:5;       //Offset=123
    uint8_t LegI2C1Error;       //Offset=128
    uint8_t LegI2C2Error;       //Offset=136
    uint8_t LegI2C1Reset;       //Offset=144
    uint8_t LegI2C2Reset;       //Offset=152
    uint8_t LegSPIRetries;       //Offset=160
    uint8_t LegMramCRC;       //Offset=168
    uint8_t LegMramRead;       //Offset=176
    uint8_t LegMramWrite;       //Offset=184
    uint8_t ICRCmdFailCRC;       //Offset=192
    uint8_t ICRCmdFailTime;       //Offset=200
    uint8_t ICRCmdFailAuthenticate;       //Offset=208
    uint8_t ICRCmdFailCommand;       //Offset=216
    uint8_t ICRCmdFailNamespace;       //Offset=224
    uint8_t LegSWVersion[2];       //Offset=232
    uint8_t LegErrorData;       //Offset=248
} legacyErrors_t; // Total Size=256 bits or 32 bytes with 0 left over
#endif
