#ifndef MAXDOWNLINK_H_RTIHU
#define MAXDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _maxSpecific_t {
    uint32_t maxTimestampUptime;       //Offset=0
    uint16_t maxTimestampEpoch;       //Offset=32
    uint8_t maxCRCerror;       //Offset=48
    uint8_t pad0;       //Offset=56
} maxSpecific_t; // Total Size=64 bits or 8 bytes with 0 left over
#endif
