#ifndef MINDOWNLINK_H_RTIHU
#define MINDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _minSpecific_t {
    uint32_t minTimestampUptime;       //Offset=0
    uint16_t minTimestampEpoch;       //Offset=32
    uint16_t minmaxResetEpoch;       //Offset=48
    uint32_t minmaxResetSecs;       //Offset=64
    uint8_t minCRCerror;       //Offset=96
    uint8_t Pad192[3];       //Offset=104
} minSpecific_t; // Total Size=128 bits or 16 bytes with 0 left over
#endif
