#ifndef MINDOWNLINK_H_RTIHU
#define MINDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _minSpecific_t {
    uint32_t minTimestampUptime;       //Offset=512
    uint16_t minTimestampEpoch;       //Offset=544
    uint16_t minmaxResetEpoch;       //Offset=560
    uint32_t minmaxResetSecs;       //Offset=576
    uint8_t minCRCerror;       //Offset=608
    uint8_t Pad192[3];       //Offset=616
} minSpecific_t; // Total Size=640 bits or 80 bytes with 0 left over
#endif
