#ifndef RADDOWNLINK_H_RTIHU
#define RADDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _radiation_t {
    uint8_t data[58];       //Offset=0
    uint8_t exp1BoardNum;       //Offset=464
    uint8_t pad219;       //Offset=472
} radiation_t; // Total Size=480 bits or 60 bytes with 0 left over
#endif
