#ifndef RADWODSPECIFICDOWNLINK_H_RTIHU
#define RADWODSPECIFICDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _radWodSpecific_t {
    uint32_t WODTimestampUptime;       //Offset=480
    uint16_t WODTimestampReset;       //Offset=512
    uint8_t WodCRCError;       //Offset=528
    uint8_t pad233;       //Offset=536
} radWodSpecific_t; // Total Size=544 bits or 68 bytes with 0 left over
#endif
