#ifndef RAGDOWNLINK_H_RTIHU
#define RAGDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _ragnarok_t {
    uint8_t data[84];       //Offset=0
} ragnarok_t; // Total Size=672 bits or 84 bytes with 0 left over
#endif
