#ifndef REALTIMEDOWNLINK_H_RTIHU
#define REALTIMEDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _realtimeSpecific_t {
    uint32_t Pad5;       //Offset=672
} realtimeSpecific_t; // Total Size=704 bits or 88 bytes with 0 left over
#endif
