#ifndef RT1ERRORSDOWNLINK_H_RTIHU
#define RT1ERRORSDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _rt1Errors_t {
    unsigned int wdReports:9;       //Offset=0
    unsigned int errorCode:5;       //Offset=9
    unsigned int taskNumber:4;       //Offset=14
    unsigned int previousTask:4;       //Offset=18
    unsigned int earlyResetCount:3;       //Offset=22
    unsigned int wasStillEarlyInBoot:1;       //Offset=25
    unsigned int valid:1;       //Offset=26
    unsigned int pad316:5;       //Offset=27
    uint32_t errorData;       //Offset=32
    uint32_t RAMCorAddr1;       //Offset=64
    uint32_t RAMCorAddr2;       //Offset=96
    uint32_t ROMCorAddr1;       //Offset=128
    uint32_t ROMCorAddr2;       //Offset=160
    uint8_t DCTCmdFailCRCCnt;       //Offset=192
    uint8_t DCTCmdFailTimeCnt;       //Offset=200
    uint8_t DCTCmdFailAuthenticateCnt;       //Offset=208
    uint8_t DCTCmdFailCommandCnt;       //Offset=216
    uint8_t DCTCmdFailNamespaceCnt;       //Offset=224
    uint8_t I2C1ErrorCnt;       //Offset=232
    uint8_t I2C2ErrorCnt;       //Offset=240
    uint8_t I2C1ResetCnt;       //Offset=248
    uint8_t I2C2ResetCnt;       //Offset=256
    uint8_t I2C1RetryCnt;       //Offset=264
    uint8_t I2C2RetryCnt;       //Offset=272
    uint8_t SPIRetryCnt;       //Offset=280
    uint8_t MramCRCCnt;       //Offset=288
    uint8_t MramRdErrorCnt;       //Offset=296
    uint8_t MramWtErrorCnt;       //Offset=304
    uint8_t FlashCorCnt;       //Offset=312
    uint8_t RamEvenCorCnt;       //Offset=320
    uint8_t RamOddCorCnt;       //Offset=328
    uint8_t PLLSlipCnt;       //Offset=336
    uint8_t ClockMonitorFailCnt;       //Offset=344
    uint8_t VIMRamParityCnt;       //Offset=352
    uint8_t CAN1RamParityCnt;       //Offset=360
    uint8_t CAN2RamParityCnt;       //Offset=368
    uint8_t DCC1ErrorCnt;       //Offset=376
    uint8_t DCC2ErrorCnt;       //Offset=384
    uint8_t N2HET2RamParityCnt;       //Offset=392
    uint8_t IOMMAccvioCnt;       //Offset=400
    uint8_t nonFatalCnt;       //Offset=408
    uint8_t SWVersion[2];       //Offset=416
    uint16_t pad362;       //Offset=432
} rt1Errors_t; // Total Size=448 bits or 56 bytes with 0 left over
#endif
