#ifndef WODSPECIFICDOWNLINK_H_RTIHU
#define WODSPECIFICDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _wodSpecific_t {
    uint32_t WODTimestampUptime;       //Offset=0
    uint16_t WODTimestampReset;       //Offset=32
    uint8_t WodCRCError;       //Offset=48
    unsigned int pad202:5;       //Offset=56
    unsigned int inScienceMode:1;       //Offset=61
    unsigned int inHealthMode:1;       //Offset=62
    unsigned int inSafeMode:1;       //Offset=63
} wodSpecific_t; // Total Size=64 bits or 8 bytes with 0 left over
#endif
