#ifndef WODSPECIFICDOWNLINK_H_RTIHU
#define WODSPECIFICDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _wodSpecific_t {
    uint32_t WODTimestampUptime;       //Offset=0
    uint16_t WODTimestampReset;       //Offset=32
    uint8_t WodCRCError;       //Offset=48
} wodSpecific_t; // Total Size=56 bits or 7 bytes with 0 left over
#endif
