#ifndef WODSPECIFICDOWNLINK_H_RTIHU
#define WODSPECIFICDOWNLINK_H_RTIHU
//Created by GenFlightStruct.py from file DownlinkSpecGolf-T.xlsx
// Do not edit this file.
#ifndef RTIHU
#error Wrong Archtecture
#endif
typedef struct  __attribute__((__packed__)) _wodSpecific_t {
    uint32_t WODTimestampUptime;       //Offset=768
    uint16_t WODTimestampReset;       //Offset=800
    uint8_t WodCRCError;       //Offset=816
    unsigned int pad202:5;       //Offset=824
    unsigned int inScienceMode:1;       //Offset=829
    unsigned int inHealthMode:1;       //Offset=830
    unsigned int inSafeMode:1;       //Offset=831
} wodSpecific_t; // Total Size=832 bits or 104 bytes with 0 left over
#endif
